### ISSUE TITLE
Dockerfile build fails: base image missing

### ISSUE THREAD

**Issue by Mohinta2892** [danifranco/BiaPy#28]
Hi Daniel,

Building the docker from `utils/env/Dockerfile` fails due to missing base image ``` nvidia/cuda:11.4.0-base-ubuntu20.04```.
I could build a docker for BiaPy after pulling a TF2 installed nvidia-base image.

Could you kindly test if the existing Docker build works at your end?
Happy to share my Dockerfile via pull request if it would be of benefit.

Best,
Samia

**Comment by danifranco** [comment]
Hello,

They have deleted that base image so you can use `nvidia/cuda:11.4.3-base-ubuntu20.04` instead ([see avaiailable tags here](https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=11.4.)). 

Best regards,

Dani

**Comment by Mohinta2892** [comment]
This works. Thanks.
